/// <reference types="vite/client" />

interface ImportMetaEnv {
    readonly DEV: boolean
    readonly PROD: boolean
    readonly MODE: string
    // Add more env variables as needed
}

interface ImportMeta {
    readonly env: ImportMetaEnv
}

/** Blog post metadata (article bodies stripped) generated by the blog-index Vite plugin. */
declare module 'virtual:blog-index' {
    import type { BlogPost } from '@/types/schema'
    const posts: BlogPost[]
    export default posts
}
